### ISSUE TITLE
lost in translation 😂

### ISSUE THREAD

**Issue by guix54** [dartungar/obsidian-emotion-picker#14] opened 2024-11-15 04:54 UTC
Hello, since the last update (or a problem with obsidian sync) the emotion translation are overrided by english for each starting...

**Comment by dartungar** [comment] 2024-11-16 08:46
@guix54 I could not reproduce it on my PC :( 
What I did is:
1. Set locale to `sv`
2. Open Emotion Picker modal to ensure translation works
3. Close Obsidian
4. Open Obsidian
5. Open Emotion Picker modal to ensure translation works

Could you provide more details about the error from your side?

**Comment by guix54** [comment] 2024-11-16 10:26
I'm not sure about the root cause (perhaps a problem with obsidian sync)
I have directly modified main.js ;-)

**Comment by dartungar** [comment] 2024-11-28 11:13
@guix54 there was a (little bit different but could cause what you've encountered) bug introduced by locale PR - this should be fixed in 1.2.1.

**Closed as completed by dartungar** 2024-11-28 11:13 UTC
